runtime: nodejs10
env: standard
instance_class: F4
automatic_scaling:
  min_instances: 2
  max_instances: 12
  target_cpu_utilization: 0.7
  max_concurrent_requests: 20
  target_throughput_utilization: 0.8
